---
# tasks file for users

# python -c "from passlib.hash import sha512_crypt; import getpass; print sha512_crypt.encrypt(getpass.getpass())"

# Create accounts
- name: create accounts
  user:
    name: "{{item.name}}"
    comment: "{{item.description|default('created by ansible')}}"
    state: present
    password: "{{item.password}}"
    shell: /bin/bash
  with_items:
    - "{{users}}"
  no_log: True
  tags: users,init

# Apply authorized keys
- name: add ssh keys
  authorized_key:
    user: "{{item.0.name}}"
    state: present
    key: "{{item.1}}"
  with_subelements:
    - "{{users}}"
    - authorized_keys
  no_log: True
  tags: users,init

